# Generated by Django 6.0.1 on 2026-02-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
